//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramVPNBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramVPNBot.Properties.Resource_en", typeof(Resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lh3.googleusercontent.com/fife/ALs6j_FJDmdxtUSbAuLjXAoSOPDmeA_UVBBCIvIRayVbSJmG3JHp6enlttqnYcQtPTtvYJIOniygzFASeWibYjD-GxkpGny2gTAqpCVo4el25n9hK6Jx8ZtWlbCp7XCYuh-tkGle7B1ERSbDiHa4RPBAmQFFDnBe_yktSWEenGYeoziIkYP3DPOsB0J81BKY25_Tq4AhNZLvqdC924Nd-XHeKRjniKiA2dp1ToaQsV0JdzvLERFh_r_0eVaDvv_BwV0FsDhTOoCD8FwumruyVwcm5Z2RClFB50xww469q0VX2UuEzrUo0q1NN5XEA6j5zIgcJh-0MzLpJkhJlZamSdfqAQDqAGw7HOJ939ZVJ10N_DaWFq9ViXnJdJBuYJRGH_nBJzk0xQtGD3463_DHx_1NcOzUxWXu1uz_RVWfMEfyPQPQn22jAWVox_K1j5FskQZo5-PxIlVMbjtFWvNKnd-md [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccessImg {
            get {
                return ResourceManager.GetString("AccessImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔑 **Доступ к VPN**
        ///
        ///Ваш доступ к VPN включает:
        ///- 🌍 Серверы по всему миру для анонимного и безопасного соединения.
        ///- 🚀 Высокая скорость соединения без ограничений.
        ///- 🛡️ Защита ваших данных и конфиденциальности..
        /// </summary>
        internal static string AccessMessage {
            get {
                return ResourceManager.GetString("AccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|6|12|Назад.
        /// </summary>
        internal static string KeyboardAccess {
            get {
                return ResourceManager.GetString("KeyboardAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string KeyboardProfile {
            get {
                return ResourceManager.GetString("KeyboardProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe|Profile|Settings|About Us|Support.
        /// </summary>
        internal static string KeyboardStart {
            get {
                return ResourceManager.GetString("KeyboardStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы выбрали подписку на **{0} месяцев**. Стоимость подписки: **${1}**.
        ///
        ///🔑 После оплаты вы получите персональный ключ доступа и инструкции по настройке VPN..
        /// </summary>
        internal static string PaymentMessage {
            get {
                return ResourceManager.GetString("PaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📌 **Имя:** {0}  
        ///🔗 **Имя пользователя:** @{1}  
        ///🆔 **ID Telegram:** {2}  
        ///🕒 **Дата регистрации:** {3}
        ///
        ///📅 **Статус подписки:** {4}  
        ///⏳ **Окончание подписки:** {5}.
        /// </summary>
        internal static string ProfileMessage {
            get {
                return ResourceManager.GetString("ProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lh3.googleusercontent.com/fife/ALs6j_FJDmdxtUSbAuLjXAoSOPDmeA_UVBBCIvIRayVbSJmG3JHp6enlttqnYcQtPTtvYJIOniygzFASeWibYjD-GxkpGny2gTAqpCVo4el25n9hK6Jx8ZtWlbCp7XCYuh-tkGle7B1ERSbDiHa4RPBAmQFFDnBe_yktSWEenGYeoziIkYP3DPOsB0J81BKY25_Tq4AhNZLvqdC924Nd-XHeKRjniKiA2dp1ToaQsV0JdzvLERFh_r_0eVaDvv_BwV0FsDhTOoCD8FwumruyVwcm5Z2RClFB50xww469q0VX2UuEzrUo0q1NN5XEA6j5zIgcJh-0MzLpJkhJlZamSdfqAQDqAGw7HOJ939ZVJ10N_DaWFq9ViXnJdJBuYJRGH_nBJzk0xQtGD3463_DHx_1NcOzUxWXu1uz_RVWfMEfyPQPQn22jAWVox_K1j5FskQZo5-PxIlVMbjtFWvNKnd-md [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StartImg {
            get {
                return ResourceManager.GetString("StartImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 Welcome to VPN Bot, your trusted partner for secure and anonymous internet access.
        ///
        ///Features:
        ///1. Protect your data with advanced encryption technologies.
        ///2. High-speed connection to servers around the world.
        ///3. Complete privacy without compromises.
        ///
        ///What you can do:
        ///1. Subscribe to the VPN service.
        ///2. Get setup instructions.
        ///3. Manage your account and access keys..
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подписка активна.
        /// </summary>
        internal static string SubscriptionStatusActive {
            get {
                return ResourceManager.GetString("SubscriptionStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подписка просрочена.
        /// </summary>
        internal static string SubscriptionStatusExpired {
            get {
                return ResourceManager.GetString("SubscriptionStatusExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет активной подписки.
        /// </summary>
        internal static string SubscriptionStatusNone {
            get {
                return ResourceManager.GetString("SubscriptionStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 Спасибо за покупку! Ваша подписка на **{0}** успешно активирована.
        ///
        ///🔑 Доступ к VPN:
        ///- Вы можете начать пользоваться VPN прямо сейчас.
        ///- Ваш доступ будет действителен до **{1}**.
        ///
        ///Если у вас возникли вопросы, пожалуйста, свяжитесь с нашей поддержкой..
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
    }
}
