//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramVPNBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramVPNBot.Properties.Resource_en", typeof(Resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lh3.googleusercontent.com/fife/ALs6j_FJDmdxtUSbAuLjXAoSOPDmeA_UVBBCIvIRayVbSJmG3JHp6enlttqnYcQtPTtvYJIOniygzFASeWibYjD-GxkpGny2gTAqpCVo4el25n9hK6Jx8ZtWlbCp7XCYuh-tkGle7B1ERSbDiHa4RPBAmQFFDnBe_yktSWEenGYeoziIkYP3DPOsB0J81BKY25_Tq4AhNZLvqdC924Nd-XHeKRjniKiA2dp1ToaQsV0JdzvLERFh_r_0eVaDvv_BwV0FsDhTOoCD8FwumruyVwcm5Z2RClFB50xww469q0VX2UuEzrUo0q1NN5XEA6j5zIgcJh-0MzLpJkhJlZamSdfqAQDqAGw7HOJ939ZVJ10N_DaWFq9ViXnJdJBuYJRGH_nBJzk0xQtGD3463_DHx_1NcOzUxWXu1uz_RVWfMEfyPQPQn22jAWVox_K1j5FskQZo5-PxIlVMbjtFWvNKnd-md [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccessImg {
            get {
                return ResourceManager.GetString("AccessImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Subscription 💳
        ///We offer various options to ensure you get VPN access tailored to your needs..
        /// </summary>
        internal static string AccessMessage {
            get {
                return ResourceManager.GetString("AccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://telegra.ph/Tutorial-How-to-Set-Up-and-Use-Outline-VPN-with-an-Access-Key-01-17.
        /// </summary>
        internal static string ActiveTutorial {
            get {
                return ResourceManager.GetString("ActiveTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Access Has Ended ⏳
        ///
        ///Hello!
        ///We noticed that your subscription has expired. To regain access, please renew your subscription—it only takes a few minutes!  
        ///
        ///If you have any questions or need assistance, feel free to contact us. We are always here to help.  
        ///
        ///Thank you for choosing us! 💙.
        /// </summary>
        internal static string ExpiredMessage {
            get {
                return ResourceManager.GetString("ExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 Congratulations! Your 24-hour trial VPN subscription has been successfully activated. 
        ///
        ///📲 You can connect right away and start enjoying secure and fast internet access. 
        ///
        ///⏰ Once the trial period ends, you can extend your subscription to continue using the service. 
        ///
        ///Thank you for choosing our service! 💙.
        /// </summary>
        internal static string FreeMessage {
            get {
                return ResourceManager.GetString("FreeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly|6 Months|12 Months|🎁 Trial Period|⬅️ Back.
        /// </summary>
        internal static string KeyboardAccess {
            get {
                return ResourceManager.GetString("KeyboardAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe|Profile.
        /// </summary>
        internal static string KeyboardExpired {
            get {
                return ResourceManager.GetString("KeyboardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 My Subscriptions|⬅️ Back.
        /// </summary>
        internal static string KeyboardFree {
            get {
                return ResourceManager.GetString("KeyboardFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay {0}⭐|⬅️ Back.
        /// </summary>
        internal static string KeyboardPayment {
            get {
                return ResourceManager.GetString("KeyboardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 My Subscriptions|⬅️ Back.
        /// </summary>
        internal static string KeyboardProfile {
            get {
                return ResourceManager.GetString("KeyboardProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe|Profile|Settings|About Us|Support.
        /// </summary>
        internal static string KeyboardStart {
            get {
                return ResourceManager.GetString("KeyboardStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Active?|⬅️ Back.
        /// </summary>
        internal static string KeyboardSubscription {
            get {
                return ResourceManager.GetString("KeyboardSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 My Subscriptions|⬅️ Back.
        /// </summary>
        internal static string KeyboardSuccess {
            get {
                return ResourceManager.GetString("KeyboardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen a {0}-month subscription. The subscription cost is {1}⭐.
        ///
        ///🔑 After payment, you will receive a personal access key and instructions for setting up the VPN..
        /// </summary>
        internal static string PaymentMessage {
            get {
                return ResourceManager.GetString("PaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📌 **Name:** {0}
        ///🔗 Username: @{1}
        ///🆔 Telegram ID: {2}
        ///🕒 Registration Date: {3}
        ///
        ///📅 Status: {4}
        ///⏳ Subscription Expiration: {5}  (UTC+0).
        /// </summary>
        internal static string ProfileMessage {
            get {
                return ResourceManager.GetString("ProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lh3.googleusercontent.com/fife/ALs6j_FJDmdxtUSbAuLjXAoSOPDmeA_UVBBCIvIRayVbSJmG3JHp6enlttqnYcQtPTtvYJIOniygzFASeWibYjD-GxkpGny2gTAqpCVo4el25n9hK6Jx8ZtWlbCp7XCYuh-tkGle7B1ERSbDiHa4RPBAmQFFDnBe_yktSWEenGYeoziIkYP3DPOsB0J81BKY25_Tq4AhNZLvqdC924Nd-XHeKRjniKiA2dp1ToaQsV0JdzvLERFh_r_0eVaDvv_BwV0FsDhTOoCD8FwumruyVwcm5Z2RClFB50xww469q0VX2UuEzrUo0q1NN5XEA6j5zIgcJh-0MzLpJkhJlZamSdfqAQDqAGw7HOJ939ZVJ10N_DaWFq9ViXnJdJBuYJRGH_nBJzk0xQtGD3463_DHx_1NcOzUxWXu1uz_RVWfMEfyPQPQn22jAWVox_K1j5FskQZo5-PxIlVMbjtFWvNKnd-md [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StartImg {
            get {
                return ResourceManager.GetString("StartImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to PutiNet! 👋
        ///Your guide to a safe and unrestricted internet. We offer reliable and fast VPN services to protect your data and ensure anonymity.
        ///
        ///💡 Why choose PutiNet?
        ///
        ///🌐 Freedom and security: Work, communicate, and enjoy the internet without limits.
        ///🚀 Forget about restrictions and enjoy unrestricted access to all your favorite services.
        ///⚡ High speed and stable performance.
        ///Start your journey to internet freedom with us!.
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 Status: {0}
        ///⏳ Valid until: {1}
        ///
        ///📊 Traffic used: {2}
        ///
        ///🔑 Your access key:
        ///{3}.
        /// </summary>
        internal static string SubscriptionMessage {
            get {
                return ResourceManager.GetString("SubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Subscription is active.
        /// </summary>
        internal static string SubscriptionStatusActive {
            get {
                return ResourceManager.GetString("SubscriptionStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Subscription has expired.
        /// </summary>
        internal static string SubscriptionStatusExpired {
            get {
                return ResourceManager.GetString("SubscriptionStatusExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚫 No active subscription.
        /// </summary>
        internal static string SubscriptionStatusNone {
            get {
                return ResourceManager.GetString("SubscriptionStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 Thank you for your purchase! Your {0} subscription has been successfully activated.
        ///
        ///🔑 VPN Access:
        ///
        ///You can start using the VPN right away.
        ///Your access will be valid until {1}.
        ///If you have any questions, please contact our support team..
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
    }
}
